apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-nginx
spec:
  replicas: 3

  selector:
    matchLabels:
      app: lms-nginx

  template:
    metadata:
      labels:
        app: lms-nginx

    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            cpu: "250m"
            memory: "200Mi"

        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: nginx-html
          mountPath: /usr/share/nginx/html

      volumes:

        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-html
          configMap:
            name: nginx-html
            items:
              - key: index.html
                path: index.html