apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: lms-mysql-server
spec:
  replicas: 1

  selector: # para criar service
    matchLabels:
      app: mysql-server
      tier: db

  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: lms-mysql-pv-claim